image: ubuntu

environment:
  GCS_BUCKET: autobuilds.grr-response.com
  GRRDOCKER_PASS:
    secure: KfgTVAdEDloHMZyjxcQ9veX5Z1f1S+AJP/eF2W/5b9M=

install:
- docker version

# Appveyor will try to build any Visual Studio projects it finds
# if we do not disable this.
build: off

build_script:
- echo "${GRRDOCKER_PASS}" | docker login -u grrshared --password-stdin
- ./appveyor/docker_build/build_docker_image.sh
- docker push grrdocker/grr

on_finish:
- docker logout || true
