branches:
  only:
    - master

image: Ubuntu1804

services:
- mysql

environment:
  GRR_ADMIN_PASS: 'e2e_tests'
  APPVEYOR_MYSQL_PASS: 'Password12!'  # See https://www.appveyor.com/docs/services-databases/#mysql

install:
- lsb_release -a
- echo "${PATH}"
- lscpu
- sudo mysqld --version
- sudo systemctl start mysql  # We need to start the MySQL service manually.
# Ignore failures due to broken packages, e.g
# https://ci.appveyor.com/project/grr/grr-ia94e/builds/21637886
- sudo apt update -qq || true
- sudo -EH ./appveyor/e2e_tests/install_mem_usage_cron.sh
- sudo -EH ./appveyor/e2e_tests/install_latest_server_deb.sh

# Appveyor will try to build any Visual Studio projects it finds
# if we do not disable this.
build: off

test_script:
- sudo -EH ./appveyor/e2e_tests/run_e2e_tests.sh
- sudo -EH ./appveyor/e2e_tests/test_repack.sh

on_finish:
- ./appveyor/e2e_tests/upload_e2e_artifacts.sh
